[tool.ruff]
# Specifies that the code should be compatible with Python 3.11
target-version = "py311"

# Specifies the rules that should be checked
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "N", # pep8-naming
    "UP", # pyupgrade
    "I", # isort
]

# Specifies the rules that should be ignored
ignore = ["E501", "N803", "N806"]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM", "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL", "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"]

# Specifies the rules that cannot be automatically fixed by the tool
unfixable = []

# Specifies the directories that should be excluded from the checks
exclude = [
    ".idea",
    ".git",
    ".ruff_cache",
    "__pypackages__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "venv",
]

# Allows for per-file ignore rules, if any are needed
per-file-ignores = { }

# Allows for unused variables when they are prefixed with an underscore
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.mccabe]
# Specifies the maximum allowed complexity for a code block
max-complexity = 10